import mongoose from 'mongoose';

const ticketSchema = new mongoose.Schema(
  {
    ticketNumber: {
      type: String,
      unique: [true, 'Ticket number must be unique']
    },

    title: {
      type: String,
      required: [true, 'Title is required'],
      trim: true,
      minlength: [3, 'Title must be at least 3 characters long'],
      maxlength: [150, 'Title cannot exceed 150 characters']
    },

    description: {
      type: String,
      required: [true, 'Description is required'],
      trim: true,
      maxlength: [2000, 'Description cannot exceed 2000 characters']
    },

    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'company',
      required: [true, 'Company is required']
    },

    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'user',
      required: [true, 'Customer is required']
    },

    assignedAgent: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'agent',
      default: null
    },

    // Originating chat session (when ticket is raised from live chat)
    chat: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'chat',
      default: null
    },

    category: {
      type: String,
      enum: ['billing', 'technical', 'account', 'general'],
      default: 'general'
    },

    priority: {
      type: String,
      enum: ['low', 'medium', 'high', 'urgent'],
      default: 'medium'
    },

    status: {
      type: String,
      // `forced_closed` = the owning customer's account was deleted; only an
      // admin can move a ticket out of this state.
      enum: ['open', 'pending', 'in_progress', 'resolved', 'closed', 'forced_closed'],
      default: 'open'
    },

    // `portal` = raised by the customer themselves from the support portal
    // (the copilot-managed flow); `dashboard` = logged by staff on their behalf.
    source: {
      type: String,
      enum: ['chat', 'email', 'dashboard', 'portal', 'api'],
      default: 'dashboard'
    },

    tags: {
      type: [String],
      default: []
    },

    // Images/PDFs attached at ticket creation — shown in the ticket summary
    // card at the top of the chat thread, not persisted as a chat message.
    attachments: [
      {
        url: { type: String, required: true },
        filename: { type: String, required: true },
        mimetype: { type: String, required: true }
      }
    ],

    // Who raised the ticket. Staff-raised tickets are what the chat sidebar's
    // "Mine" filter keys off; customer-raised ones carry the customer's id.
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      refPath: 'createdByModel',
      default: null
    },

    createdByModel: {
      type: String,
      enum: ['admin', 'agent', 'user'],
      default: 'user'
    },

    // AI engine fields
    sentimentScore: {
      type: Number,
      min: 1,
      max: 5,
      default: 3
    },

    intentLabel: {
      type: String,
      enum: ['simple_faq', 'billing_issue', 'technical_problem', 'escalate_human', 'feedback'],
      default: null
    },

    // 3-sentence briefing generated by Claude on escalation
    aiSummary: {
      type: String,
      default: null
    },

    slaBreached: {
      type: Boolean,
      default: false
    },

    // Timestamps
    firstResponseAt: {
      type: Date,
      default: null
    },

    escalatedAt: {
      type: Date,
      default: null
    },

    resolvedAt: {
      type: Date,
      default: null
    },

    closedAt: {
      type: Date,
      default: null
    },

    lastMessageAt: {
      type: Date,
      default: Date.now
    },

    // Set the first time the customer replies *after* the AI's opening message.
    // A ticket reads as "New" until this exists — the AI starting the
    // conversation must not make it look like the customer engaged.
    customerRepliedAt: {
      type: Date,
      default: null
    },

    // Set to "unassigned" when a ticket escalates but no agent was eligible, so
    // the queue is visible instead of the ticket quietly sitting in
    // in_progress with nobody on it. Cleared on assignment.
    escalationState: {
      type: String,
      enum: ["unassigned", null],
      default: null
    },

    // Makes reopen/resolve cycles auditable. Without it there is no way to
    // tell a ticket resolved once from one resolved, reopened and resolved
    // again — exactly the case the resolvedAt guard used to get wrong.
    statusHistory: [
      {
        _id: false,
        from: { type: String },
        to: { type: String },
        by: { type: mongoose.Schema.Types.ObjectId },
        role: { type: String },
        at: { type: Date, default: Date.now }
      }
    ]
  },
  { timestamps: true }
);

// Date.now().slice(-6) collided outright for two tickets created in the same
// millisecond — and ticketNumber carries a unique index, so the second create
// threw. Millisecond timestamp in base36 (monotonic, so numbers still sort by
// age) plus random entropy to break ties within a tick.
ticketSchema.pre('save', function () {
  if (!this.ticketNumber) {
    const stamp = Date.now().toString(36).toUpperCase().slice(-6);
    const salt = Math.random().toString(36).toUpperCase().slice(2, 6);
    this.ticketNumber = `TKT-${stamp}${salt}`;
  }
});

// Every list view filters by company and then by status or assignee, so these
// two cover the hot paths and keep those queries off a collection scan.
ticketSchema.index({ companyId: 1, status: 1, createdAt: -1 });
ticketSchema.index({ companyId: 1, assignedAgent: 1 });

const ticketModel = mongoose.model('ticket', ticketSchema);
export default ticketModel;
