import mongoose from 'mongoose';

const ticketSchema = new mongoose.Schema(
  {
    ticketNumber: {
      type: String,
      unique: [true, 'Ticket number must be unique']
    },

    title: {
      type: String,
      required: [true, 'Title is required'],
      trim: true,
      minlength: [3, 'Title must be at least 3 characters long'],
      maxlength: [150, 'Title cannot exceed 150 characters']
    },

    description: {
      type: String,
      required: [true, 'Description is required'],
      trim: true,
      maxlength: [2000, 'Description cannot exceed 2000 characters']
    },

    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'company',
      required: [true, 'Company is required']
    },

    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'user',
      required: [true, 'Customer is required']
    },

    assignedAgent: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'agent',
      default: null
    },

    // Originating chat session (when ticket is raised from live chat)
    chat: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'chat',
      default: null
    },

    category: {
      type: String,
      enum: ['billing', 'technical', 'account', 'general'],
      default: 'general'
    },

    priority: {
      type: String,
      enum: ['low', 'medium', 'high', 'urgent'],
      default: 'medium'
    },

    status: {
      type: String,
      enum: ['open', 'pending', 'in_progress', 'resolved', 'closed'],
      default: 'open'
    },

    // `portal` = raised by the customer themselves from the support portal
    // (the copilot-managed flow); `dashboard` = logged by staff on their behalf.
    source: {
      type: String,
      enum: ['chat', 'email', 'dashboard', 'portal', 'api'],
      default: 'dashboard'
    },

    tags: {
      type: [String],
      default: []
    },

    // AI engine fields
    sentimentScore: {
      type: Number,
      min: 1,
      max: 5,
      default: 3
    },

    intentLabel: {
      type: String,
      enum: ['simple_faq', 'billing_issue', 'technical_problem', 'escalate_human', 'feedback'],
      default: null
    },

    // 3-sentence briefing generated by Claude on escalation
    aiSummary: {
      type: String,
      default: null
    },

    slaBreached: {
      type: Boolean,
      default: false
    },

    // Timestamps
    firstResponseAt: {
      type: Date,
      default: null
    },

    escalatedAt: {
      type: Date,
      default: null
    },

    resolvedAt: {
      type: Date,
      default: null
    },

    closedAt: {
      type: Date,
      default: null
    },

    lastMessageAt: {
      type: Date,
      default: Date.now
    }
  },
  { timestamps: true }
);

ticketSchema.pre('save', function () {
  if (!this.ticketNumber) {
    this.ticketNumber = 'TKT-' + Date.now().toString().slice(-6);
  }
  ;
});

const ticketModel = mongoose.model('ticket', ticketSchema);
export default ticketModel;
