# Base image
FROM node:20-alpine

# Create app directory
WORKDIR /app

# Copy package files first
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Start app
CMD ["node", "server.js"]
