// Solutions by team type. Describe what AideDesk does for each; no outcome
// percentages unless the product owner supplies real figures.
export const SEGMENTS = [
  {
    id: "startups",
    short: "Startups",
    name: "For startups",
    icon: "rocket_launch",
    hook: "A shared inbox that won't need replacing as you grow.",
    problem: "Founders answer support from a shared email inbox. Requests get missed, and nobody knows who replied to what.",
    solution: "Turn every email and chat into a ticket with an owner. The AI copilot handles routine questions so the team can stay focused on building.",
    flow: [
      ["Connect your support email", "Messages become tickets automatically."],
      ["Add the chat widget", "Customers reach you from your site."],
      ["Let AI take the first pass", "Routine questions get an answer right away."],
      ["Reply as a team", "Assign, note and resolve together."],
    ],
    features: ["Shared ticket queue", "Live chat widget", "AI copilot", "Customer portal", "Mobile-friendly", "Free plan"],
    plan: "Free or Starter",
    cta: { label: "Start free", to: "/signup" },
  },
  {
    id: "small-business",
    short: "Small business",
    name: "For small businesses",
    icon: "storefront",
    hook: "Look organised to customers without hiring a support lead.",
    problem: "A few people juggle support alongside other work. Customers chase updates because they can't see progress.",
    solution: "Give customers a portal that shows status in plain language, and give your team saved views so the right person picks up each request.",
    flow: [
      ["Invite your team", "Everyone gets the agent workspace."],
      ["Share the portal link", "Customers track their own requests."],
      ["Use saved views", "“Assigned to me” keeps focus."],
      ["Close the loop", "Customers rate the help they got."],
    ],
    features: ["Customer portal", "Saved views", "Internal notes", "Satisfaction ratings", "Email + chat", "Roles"],
    plan: "Starter",
    cta: { label: "Start free", to: "/signup" },
  },
  {
    id: "growing",
    short: "Growing",
    name: "For growing companies",
    icon: "trending_up",
    hook: "Keep response times steady while volume climbs.",
    problem: "Volume is rising faster than headcount. Urgent tickets hide among routine ones and SLAs slip without warning.",
    solution: "Set SLA targets by priority and let AI triage sort incoming work. The “needs attention” list shows what will breach next.",
    flow: [
      ["Define SLA targets", "Per priority, with business hours."],
      ["Turn on AI triage", "Category and priority set on arrival."],
      ["Work the risk list", "Agents see what breaches next."],
      ["Review weekly", "Analytics show response trends."],
    ],
    features: ["SLA policies", "AI triage", "Workload view", "Analytics", "Teams", "Bulk actions"],
    plan: "Business",
    cta: { label: "Start a trial", to: "/signup" },
  },
  {
    id: "enterprise",
    short: "Enterprise",
    name: "For enterprises",
    icon: "apartment",
    hook: "Multiple teams, strict access, clear accountability.",
    problem: "Several support teams, regions and products share one tool. Access needs to be controlled and changes need to be traceable.",
    solution: "Separate workspaces, role-based access and live session revocation, with automation to route work to the right team.",
    flow: [
      ["Set up workspaces", "One per team, region or product."],
      ["Assign roles", "Admins, agents and customers."],
      ["Route with rules", "Enterprise tickets go to the right team."],
      ["Monitor activity", "See changes across the system."],
    ],
    features: ["Multiple workspaces", "Role-based access", "Session revocation", "Automation", "SSO (roadmap)", "Dedicated support"],
    plan: "Enterprise",
    cta: { label: "Talk to sales", to: "/demo" },
  },
  {
    id: "support-teams",
    short: "Support teams",
    name: "For support teams",
    icon: "support_agent",
    hook: "A faster day for the people answering tickets.",
    problem: "Agents switch between tabs to find customer history, and lose time rewriting the same answers.",
    solution: "Customer context sits beside every conversation, with canned responses and AI-suggested replies in the composer.",
    flow: [
      ["Open the workspace", "Your queue, ranked by urgency."],
      ["See the full picture", "History, notes and plan in one panel."],
      ["Reply faster", "Canned responses and AI suggestions."],
      ["Hand off cleanly", "Assign with an internal note."],
    ],
    features: ["Agent workspace", "Canned responses", "AI suggestions", "Customer context", "⌘K search", "Internal notes"],
    plan: "Starter or Business",
    cta: { label: "Start free", to: "/signup" },
  },
  {
    id: "customer-success",
    short: "Customer success",
    name: "For customer success teams",
    icon: "favorite",
    hook: "Spot at-risk accounts before renewal conversations.",
    problem: "CS managers don't see support friction until a customer raises it at renewal.",
    solution: "Customer profiles show open tickets, satisfaction and renewal tags, so CS can step in early with the full story.",
    flow: [
      ["Tag key accounts", "Plan, renewal date, owner."],
      ["Watch the timeline", "Every ticket and chat in one place."],
      ["Leave notes for support", "Context that travels with the customer."],
      ["Follow up proactively", "Reach out before renewal."],
    ],
    features: ["Customer profiles", "Tags", "Activity timeline", "Customer notes", "CSAT history", "Company view"],
    plan: "Business",
    cta: { label: "Start a trial", to: "/signup" },
  },
  {
    id: "saas",
    short: "SaaS",
    name: "For SaaS companies",
    icon: "cloud",
    hook: "In-app chat and technical triage built for software.",
    problem: "Technical questions bounce between support and engineering, and customers repeat themselves at every step.",
    solution: "Chat inside your product, AI-drafted tickets with the details engineering needs, and escalation that keeps the thread intact.",
    flow: [
      ["Embed chat in your app", "Customers ask without leaving."],
      ["AI gathers details", "Version, error and steps, drafted as a ticket."],
      ["Escalate with context", "Engineering sees the whole thread."],
      ["Update the customer", "From the same conversation."],
    ],
    features: ["In-app chat", "AI-drafted tickets", "Escalation", "Attachments", "Webhooks (roadmap)", "API (roadmap)"],
    plan: "Business",
    cta: { label: "Start a trial", to: "/signup" },
  },
];
